//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hinh_anh
    {
        public int ID_Hinhanh { get; set; }
        public int ID_San_Pham { get; set; }
        public string Hinhchinh { get; set; }
        public string Hinh1 { get; set; }
        public string Hinh2 { get; set; }
        public string Hinh3 { get; set; }
        public Nullable<int> Trangthai { get; set; }
    
        public virtual San_pham San_pham { get; set; }
    }
}
