//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khuyen_mai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Khuyen_mai()
        {
            this.San_pham = new HashSet<San_pham>();
        }
    
        public int ID_Khuyenmai { get; set; }
        public string Ten_giamgia { get; set; }
        public Nullable<System.DateTime> Ngay_batdau { get; set; }
        public Nullable<System.DateTime> Ngay_ketthuc { get; set; }
        public Nullable<int> Mucgiamgia { get; set; }
        public Nullable<int> trangthai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<San_pham> San_pham { get; set; }
    }
}
