//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopBanGiayEntities : DbContext
    {
        public ShopBanGiayEntities()
            : base("name=ShopBanGiayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chi_tiet_don_hang> Chi_tiet_don_hang { get; set; }
        public virtual DbSet<Danh_muc> Danh_muc { get; set; }
        public virtual DbSet<Don_hang> Don_hang { get; set; }
        public virtual DbSet<Hinh_anh> Hinh_anh { get; set; }
        public virtual DbSet<Khuyen_mai> Khuyen_mai { get; set; }
        public virtual DbSet<Kich_thuoc> Kich_thuoc { get; set; }
        public virtual DbSet<Nguoi_dung> Nguoi_dung { get; set; }
        public virtual DbSet<Nhom_Danh_Muc> Nhom_Danh_Muc { get; set; }
        public virtual DbSet<San_pham> San_pham { get; set; }
        public virtual DbSet<Slide> Slides { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Thanh_toan> Thanh_toan { get; set; }
        public virtual DbSet<Vai_tro> Vai_tro { get; set; }
        public virtual DbSet<Van_chuyen> Van_chuyen { get; set; }
    }
}
