//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoi_dung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nguoi_dung()
        {
            this.Don_hang = new HashSet<Don_hang>();
            this.Thanh_toan = new HashSet<Thanh_toan>();
        }
    
        public int ID_Nguoidung { get; set; }
        public string Ten_Nguoidung { get; set; }
        public Nullable<System.DateTime> Ngay_sinh { get; set; }
        public Nullable<int> ID_vaitro { get; set; }
        public string Hinh_anh { get; set; }
        public string Dia_chi { get; set; }
        public string Email { get; set; }
        public Nullable<int> So_DT { get; set; }
        public string Tai_Khoan { get; set; }
        public string Mat_Khau { get; set; }
        public Nullable<int> Trangthai { get; set; }
        public Nullable<int> Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Don_hang> Don_hang { get; set; }
        public virtual Vai_tro Vai_tro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thanh_toan> Thanh_toan { get; set; }
    }
}
