//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class San_pham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public San_pham()
        {
            this.Chi_tiet_don_hang = new HashSet<Chi_tiet_don_hang>();
            this.Hinh_anh = new HashSet<Hinh_anh>();
            this.Kich_thuoc = new HashSet<Kich_thuoc>();
        }
    
        public int ID_Sanpham { get; set; }
        public string Tensanpham { get; set; }
        public int ID_Khuyenmai { get; set; }
        public int ID_Danh_Muc { get; set; }
        public string Mota { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
        public Nullable<int> Trangthai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_tiet_don_hang> Chi_tiet_don_hang { get; set; }
        public virtual Danh_muc Danh_muc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hinh_anh> Hinh_anh { get; set; }
        public virtual Khuyen_mai Khuyen_mai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kich_thuoc> Kich_thuoc { get; set; }
    }
}
