//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int ID_Slide { get; set; }
        public string Hinh_anh { get; set; }
        public string Tieu_de { get; set; }
        public string Noi_dung { get; set; }
        public Nullable<int> Trangthai { get; set; }
    }
}
