//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thanh_toan
    {
        public int ID_ThanhToan { get; set; }
        public int ID_Donhang { get; set; }
        public int ID_Nguoidung { get; set; }
        public Nullable<System.DateTime> Ngay_thanh_toan { get; set; }
        public Nullable<decimal> So_tien { get; set; }
        public Nullable<int> Trangthai { get; set; }
    
        public virtual Don_hang Don_hang { get; set; }
        public virtual Nguoi_dung Nguoi_dung { get; set; }
    }
}
