//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Van_chuyen
    {
        public int ID_van_chuyen { get; set; }
        public int ID_don_hang { get; set; }
        public Nullable<System.DateTime> Ngay_giao { get; set; }
        public Nullable<System.DateTime> Ngay_Nhan { get; set; }
        public Nullable<int> Trangthai { get; set; }
    
        public virtual Don_hang Don_hang { get; set; }
    }
}
